name: ALIEN 4 Cloud Documentation Portal
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highligter: pygments
encoding: UTF-8

categories-list: ["DOCUMENTATION", "DOCUMENTATION-1.1.0", "DOCUMENTATION-1.2.0", "DOCUMENTATION-1.3.0", "DOCUMENTATION-1.4.0", "DOCUMENTATION-2.0.0","RELEASE_NOTES", "DEVELOPER_GUIDE", "ROADMAP"]

stable-version: "1.4.3.1"
premium-stable-version: "1.4.3.1"
last-version: "2.0.0-SM3"
last-snapshot: "2.0.0-SNAPSHOT"
old-stables: ["1.4.0"]
log_app_version: 1.4.3.1

pullrequesturl: http://prose.io/#alien4cloud/alien4cloud.github.io/edit/sources/

lunr_search:
  excludes: ["css/*", "documentation/1.2.0/*", "documentation/1.3.0/*", "documentation/2.0.0/*"]
